services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST}:${DB_PORT}:5432"

  my_app:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: sh -c "poetry run alembic upgrade head && poetry run python -m main"
    restart: always
    env_file:
      - .env
    environment:
      APP_PORT: $APP_PORT
      APP_HOST: $APP_HOST
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "${APP_HOST}:${APP_PORT}:8000"
    depends_on:
      - db

  web:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    volumes:
      - web-static:/app/build
    env_file:
      - .env
    environment:
      REACT_APP_BASE_URL: $REACT_APP_BASE_URL

  nginx:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html
    depends_on:
      - my_app
      - web

volumes:
  db-data:
  web-static:
